### ISSUE TITLE
Changing the top scroll Button

### ISSUE THREAD

**Issue by trishit78** [Karamraj/BookTown#107]
Earlier the button was Not looking that much good, 
it was just a text for TOP
I have updated it to an Up Arrow symbol
With just a minor change of Unicode 

Now the Button looks like this :
<img width="960" alt="image" src="https://github.com/Karamraj/BookTown/assets/90523629/ddcde765-8134-42e5-99bc-3d647f81a52d">

It will be easier to understand for the users and Looks better Than TOP written on it

**Comment by yashhhhh1** [comment]
Hi @trishit78 

can you please assign the task

**Comment by yashhhhh1** [comment]
![Screenshot 2023-10-07 185904](https://github.com/Karamraj/BookTown/assets/115985795/565f84ad-6662-48da-8224-e1dc1e9daec4)

**Comment by trishit78** [comment]
No, man I found the bug earlier, and  I created this issue, so technically this issue belongs to me 
There are many issues in this project, u can create some other issues and work on them, I already have coded it, waiting for the maintainer to assign the issue to me, so I can create the Pr
@yashhhhh1

**Comment by yashhhhh1** [comment]
ok @trishit78

**Comment by trishit78** [comment]
@Karamraj   can u assign this task to me?

**Comment by Karamraj** [comment]
@trishit78 Assigned.

**Comment by trishit78** [comment]
i have created a PR, can u merge it?
@Karamraj
