### ISSUE TITLE
Bug Fix Proposal: Consistent Styling for Book Display and 'Add to Cart' Button(verity)

### ISSUE THREAD

**Issue by akshitajaiswal2908** [Karamraj/BookTown#132]
I've identified a styling inconsistency in the website where a single book(verity) and the 'Add to Cart' button appear differently from the rest, making the overall presentation less polished. This bug detracts from the website's overall aesthetic and user experience. I propose fixing this issue to ensure a uniform and visually pleasing design for all book listings and the 'Add to Cart' button. This enhancement will contribute to a more cohesive and visually appealing website.
![image](https://github.com/Karamraj/BookTown/assets/116386619/3f27ca71-dcd7-4a34-9591-04869c356ce4)

**Comment by akshitajaiswal2908** [comment]
please assign it to me!!
@Karamraj

**Comment by Karamraj** [comment]
@akshitajaiswal2908 Assigned.

Make sure to join the discord server of all contributors - https://discord.gg/fgMHHP4Kcq
