### ISSUE TITLE
change color in Footer

### ISSUE THREAD

**Issue by Ujjwal807** [Karamraj/BookTown#136]
Change the color of the email ID and phone number links are blue in color that does not look good and are not visible perfectly so changing this color may increase User experience.

Please assign this task to me so I can fix this issue.

![image](https://github.com/Karamraj/BookTown/assets/121127299/5123dd52-2299-4328-ae3b-20fde2fd3651)

**Comment by Karamraj** [comment]
@Ujjwal807 Assigned.

Make sure to join the discord server of all contributors - https://discord.gg/fgMHHP4Kcq
