### ISSUE TITLE
Redesign the contact section

### ISSUE THREAD

**Issue by Ujjwal807** [Karamraj/BookTown#137]
Your contact form is not looking good I will update the UI to a Glassphormism design that will look good.
Please assign this task to me so i can fix this

![image](https://github.com/Karamraj/BookTown/assets/121127299/f6dc8e76-c938-48f8-aed7-679864361763)

**Comment by Karamraj** [comment]
@Ujjwal807 Assigned.

Make sure to join the discord server of all contributors - https://discord.gg/fgMHHP4Kcq
