### ISSUE TITLE
aligning the best.html page navbar to center alligned

### ISSUE THREAD

**Issue by KrishayNair** [Karamraj/BookTown#140]
![image](https://github.com/Karamraj/BookTown/assets/98453988/6f997a48-70e0-4167-8cf5-3f5404eac9d7)
alligning it to vertically center. for hacktoberfest 2023

**Comment by Karamraj** [comment]
@KrishayNair Assigned.

Make sure to join the discord server of all contributors - https://discord.gg/fgMHHP4Kcq

**Comment by ramchandra06032004** [comment]
hello sir,please assign this issue to me am interesting in this and able to do in less time.

**Comment by Karamraj** [comment]
@ramchandra06032004 Assigned.
