### ISSUE TITLE
updating footer in Newest books section

### ISSUE THREAD

**Issue by DivyanshiNarang** [Karamraj/BookTown#142]
I can improve the footer in Newest Books Section.

![image](https://github.com/Karamraj/BookTown/assets/74779601/a4e8176e-dc88-473b-bc36-f094c9cea096)

**Comment by Karamraj** [comment]
@DivyanshiNarang Assigned.

Make sure to join the discord server of all contributors - https://discord.gg/fgMHHP4Kcq
