### ISSUE TITLE
bug: icons alignment in footer 

### ISSUE THREAD

**Issue by DivyanshiNarang** [Karamraj/BookTown#143]
social icons are not properly aligned in footer of Home Page.

![image](https://github.com/Karamraj/BookTown/assets/74779601/1a1ea5a6-d7ac-4caf-8721-66ef8841980f)

**Comment by Karamraj** [comment]
@DivyanshiNarang Assigned.

Make sure to join the discord server of all contributors - https://discord.gg/fgMHHP4Kcq

**Comment by Nupur19nj** [comment]
If it's still not done, can you please assign me this task!
