### ISSUE TITLE
[Documentation Addition]: Adding links of official documentation 

### ISSUE THREAD

**Issue by DivyanshiNarang** [Karamraj/BookTown#154]
Official documentation links are not added to these buttons in README.md. We can add official documentation links of the respective technologies used so that it will be helpful for new contributors.

![Screenshot 2023-10-17 234230](https://github.com/Karamraj/BookTown/assets/74779601/0e2070c0-5e69-4da9-a4b6-692a59c1b506)

**Comment by Saharshjain78** [comment]
Can you provide more information about this task?
