### ISSUE TITLE
[Bug] Contact us page is not visible

### ISSUE THREAD

**Issue by Mayank-Sharma17** [Karamraj/BookTown#163]
**Describe the bug**
Contact Us page is not visible

**To Reproduce**
1. Go to home page
2. Click on contact us button in navbar
3. See error

**Expected behavior**
When a user clicks on the Contact Us page, it should be visible !

**Screenshots**
![Screenshot 2023-10-21 005040](https://github.com/Karamraj/BookTown/assets/113251342/193e2d8b-9ef9-44b1-b021-d46b7175cabe)

**Desktop (please complete the following information):**
 - OS: windows
 - Browser: firefox, chrome
 - Version [updated]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Nupur19nj** [comment]
Can you please assign me this?
