### ISSUE TITLE
UI Improvement for add to cart

### ISSUE THREAD

**Issue by Anuragpal010104** [Karamraj/BookTown#17]
I want to enhance the alert when any product is added. If possible assign this issue to under hacktoberfest 2023. Thanks for consideration :).

**Comment by Karamraj** [comment]
@Anuragpal010104 Assigned. Please make sure star the repo and follow me on github (https://github.com/karamraj).

Join Discord Server for this repo - https://discord.gg/SH6XRrHs8E

**Comment by balkishan69** [comment]
hey @Karamraj i have solved the issue and also created a PR with a screenshot, kindly merge my PR

**Comment by balkishan69** [comment]
hey @Karamraj please check my PR,

**Comment by Karamraj** [comment]
@balkishan69 Please tag this issue in your PR.

**Comment by balkishan69** [comment]
@Karamraj Done, kindly check
