### ISSUE TITLE
no title image 

### ISSUE THREAD

**Issue by KrishayNair** [Karamraj/BookTown#20]
I can add a title image using the current logo of booktown. @Karamraj 
![image](https://github.com/Karamraj/BookTown/assets/98453988/9b21d101-1165-4d75-b130-0b7ed08f480d)

This is for HacktoberFest 2023

**Comment by Toyin5** [comment]
Do you mean favicon?
If yes, assign it to me

**Comment by Karamraj** [comment]
> Do you mean favicon?
> If yes, assign it to me

Join our discord server - https://discord.gg/T8m6Qh5aw5
