### ISSUE TITLE
Need so much contributions

### ISSUE THREAD

**Issue by kom-senapati** [Karamraj/BookTown#3]
No logo or title on the website
![image](https://github.com/Karamraj/BookTown/assets/92045934/9d9788ef-7194-458a-8291-e8d312af5477)

Very bad choice of colours and alignment
![image](https://github.com/Karamraj/BookTown/assets/92045934/e207482a-9adf-490b-a70c-8bab394f351b)

Dont need any underlines here 
![image](https://github.com/Karamraj/BookTown/assets/92045934/25aa81bc-0ff1-4330-a565-7b746a1da7c2)

Empty sections like
![image](https://github.com/Karamraj/BookTown/assets/92045934/da0c2b62-bf6f-486c-8b4b-d4489e060bb8)

**Comment by harshsinghcs** [comment]
I'm Interested to slove this issue.

**Comment by kom-senapati** [comment]
Please assign me (@kom-senapati) and @harshsinghcs this issue under hacktoberfest.

**Comment by Karamraj** [comment]
@kom-senapati @harshsinghcs Join Discord Server for this repo - https://discord.gg/SH6XRrHs8E

**Comment by vaishnavibn14** [comment]
Hi @kom-senapati , 

I would like to work on this issue. Could you please assign me this issue under hacktoberfest.

**Comment by kom-senapati** [comment]
@vaishnavibn14 We are the assignees of this issue.
