### ISSUE TITLE
make the footer colorful and 

### ISSUE THREAD

**Issue by khadar1020** [Karamraj/BookTown#31]
the footer letters are not visible clearly we can increase the styling of the footer and when we hover also there is no under-line effect also we can add it please assign me this issue @Karamraj
![hack2](https://github.com/Karamraj/BookTown/assets/124120102/70fe4dcd-a90f-4419-8a8b-194b028c8287)

**Comment by Karamraj** [comment]
@khadar1020 Assigned.

Join our discord server - https://discord.gg/T8m6Qh5aw5
