### ISSUE TITLE
Error page

### ISSUE THREAD

**Issue by khadar1020** [Karamraj/BookTown#32]
the error is having a header of clumsy words we can remove the header and we can just put the logo of the  book town please assign me this issue @Karamraj 
![hack3](https://github.com/Karamraj/BookTown/assets/124120102/de5ac9ba-1d15-4ac1-9d81-26211e033213)

**Comment by Karamraj** [comment]
@khadar1020 Assigned. Join our discord server (This Repo) - https://discord.gg/T8m6Qh5aw5
