### ISSUE TITLE
Bug: Welcome Bar Alignment Issue

### ISSUE THREAD

**Issue by Karamraj** [Karamraj/BookTown#34]
Alignment issue in the following image:

![image](https://github.com/Karamraj/BookTown/assets/92857243/07e90df7-0a3f-4f0f-bf77-a55f4620b2c5)

**Comment by ayu5hagarwal** [comment]
can you assign me this

**Comment by Karamraj** [comment]
@ayu5hagarwal Assigned.

**Comment by ayu5hagarwal** [comment]
Sir this is solved,you can close it.
