### ISSUE TITLE
Bug: Menu Bar Too Big

### ISSUE THREAD

**Issue by Karamraj** [Karamraj/BookTown#35]
Menu bar is too big and not looking good currently.

![image](https://github.com/Karamraj/BookTown/assets/92857243/155e5f8e-44ef-4216-8acc-e9772c8265d7)

**Comment by ZealinShubh** [comment]
Can I contribute to fix this?

**Comment by Karamraj** [comment]
@ZealinShubh Sure. I will assign you.

Make sure to join our official discord server - https://discord.gg/fHhuaM3c

**Comment by shubhanshurav** [comment]
@Karamraj, I want to work on this issue, please assign me.
