### ISSUE TITLE
Bug: Newest Book

### ISSUE THREAD

**Issue by Karamraj** [Karamraj/BookTown#36]
Newest book isn't visible properly.

![image](https://github.com/Karamraj/BookTown/assets/92857243/3c57b4ea-30bd-4c4e-9390-cfe3dc4ac2ba)

**Comment by ayu5hagarwal** [comment]
can you assign it to me.

**Comment by Karamraj** [comment]
@ayu5hagarwal Assigned. Make sure to join our discord so you cal collaborate with other contributors of this repo - https://discord.gg/dbE2YUGH

**Comment by shubhanshurav** [comment]
@Karamraj , please assign me this issue
