### ISSUE TITLE
Footer links are not working!

### ISSUE THREAD

**Issue by habeebmoosa** [Karamraj/BookTown#42]
The footer links are not redirecting to respected social media accounts as well as copyright link is also not redirecting to itself. I want to work on this and solve the issue.
![image](https://github.com/Karamraj/BookTown/assets/106877248/ffe0974c-ef36-4a62-a390-6c034ad0dbe8)

**Comment by Karamraj** [comment]
@habeebmoosa Assigned.

Make sure to join discord server of this repo - https://discord.gg/MFFRBBag

**Comment by shubhanshurav** [comment]
@Karamraj , please assign me this issue,
