### ISSUE TITLE
Footer Misspelling of Words

### ISSUE THREAD

**Issue by dyarawilliams** [Karamraj/BookTown#47]
In the footer, I found that there was a misspelling of the words purchasing(perchesing) and varieties(verieties). Could you please assign me to this task as a contributor? I'm participating in hacktoberfest this year and would love to contribute to this project. If possible could you label this hacktoberfest-accepted and hacktoberfest

**Comment by dyarawilliams** [comment]
@Karamraj

**Comment by Karamraj** [comment]
@dyarawilliams Assigned.

Make sure to join our discord - https://github.com/Karamraj/BookTown

**Comment by dyarawilliams** [comment]
Thank you @Karamraj I'll get right to it.

**Comment by dyarawilliams** [comment]
#48
