### ISSUE TITLE
i will fix navbar in Mobile View. Hamburger menu is not aligned properly. 

### ISSUE THREAD

**Issue by akbar543** [Karamraj/BookTown#5]
Please assign me this issue for hacktoberfest.
![image](https://github.com/Karamraj/BookTown/assets/92615577/d8a74b30-5502-4366-8c7b-50afd9240894)

**Comment by Karamraj** [comment]
@akbar543 Please star the repository and make sure to follow me (https://github.com/Karamraj/).

**Comment by Karamraj** [comment]
@akbar543 Please star the repository and make sure to follow me (https://github.com/Karamraj/).

**Comment by akbar543** [comment]
I have starred the repository and followed you. I have fixed the issue and made a pull request.
