### ISSUE TITLE
Bug: Best of Novels

### ISSUE THREAD

**Issue by Karamraj** [Karamraj/BookTown#57]
This sections needs to be fixed so that it have all books slider of equal size.

![image](https://github.com/Karamraj/BookTown/assets/92857243/56812189-cf94-440c-a672-437d30ba4790)

**Comment by adityakhadeak** [comment]
I want to work on this bug please assign this work to me

**Comment by Karamraj** [comment]
@adityakhadeak Assigned.

Make sure to join the discord server of all contributors of this repo - https://discord.gg/7Ja25e3w
