### ISSUE TITLE
Bug: Clicking on Logo leads Error

### ISSUE THREAD

**Issue by Karamraj** [Karamraj/BookTown#60]
When we click on Logo it leads to Error 404 Page.

![image](https://github.com/Karamraj/BookTown/assets/92857243/7fc7612c-8645-42c1-8831-4e19cbe46083)

**Comment by habeebmoosa** [comment]
Hello, I want to work on this issue. Can you assign me?

**Comment by AbhineshJha** [comment]
hey @Karamraj , i love to work on this ... if u assign me this issue .

**Comment by akbar543** [comment]
Please assign me this issue as a part of hacktoberfest.

**Comment by Karamraj** [comment]
Fixed
