### ISSUE TITLE
Bug: Book Not Getting Added to Cart

### ISSUE THREAD

**Issue by Karamraj** [Karamraj/BookTown#61]
If we add any book to the cart it isn't getting added to the cart. And after clicking on Purchase we get another Prompt "Item Added to Cart".

Uploading BookTown HomePage - Google Chrome 2023-10-03 11-19-20.mp4…

**Comment by Karamraj** [comment]
https://github.com/Karamraj/BookTown/assets/92857243/426393d2-0423-4174-a611-2ebd9a244198

**Comment by Yasir761** [comment]
Hey @Karamraj, can you please assign me this under Hacktoberfest tag?

**Comment by Karamraj** [comment]
@Yasir761 Assigned.

Join The Discord of All Contributors of this repo - https://discord.gg/3E8QXXps

**Comment by Yasir761** [comment]
@Karamraj, I guess it is happening because of CORS policy, because when I ran it locally it's working fine.

**Comment by Karamraj** [comment]
Oh Okay.
