### ISSUE TITLE
Book edges got cut off

### ISSUE THREAD

**Issue by jovyllebermudez** [Karamraj/BookTown#83]
![image](https://github.com/Karamraj/BookTown/assets/73716444/68af348e-3781-47c4-9c8d-72e886efa839)

these edges of the books got cut off. Can you @Karamraj  asign this to me.

**Comment by Karamraj** [comment]
@jovyllebermudez Assigned.

Join The Discord Server - https://discord.gg/dGArYJ3e

**Comment by jovyllebermudez** [comment]
thanks, fixed, making the PR now, and already joined.
