### ISSUE TITLE
Assests optimization , "Read philosophy" misalignment, "Best of philosophy cards" redesign required

### ISSUE THREAD

**Issue by aditya4567uk** [Karamraj/BookTown#85]
Assets is not optimized as per web standards , 
"Read philosophy" section not aligned properly, 
"Best of philosophy cards" section overflowing

can you please assign me these issues , i can fix it up quickly

**Comment by Karamraj** [comment]
@aditya4567uk Assigned.

Join The Discord Server - https://discord.gg/dGArYJ3e

**Comment by aditya4567uk** [comment]
hi @Karamraj the work has been done :-

solved github icon error in footer line
Item Cards (thumb wrapper section) alignment and margins fixed
Best of booktown , best deals, best of philosophy , best of selef developement ,  best of novels section ALIGNMENT and postioning improved
Global margin (left, right) now visible IMPROVED UI an visiblity
Added best reader friendly font (Poppins 500 medium)
assests optimization done for faster loading ..

Can you guide how to merge my modified code to yours?
