### ISSUE TITLE
in philosophy page 

### ISSUE THREAD

**Issue by khadar1020** [Karamraj/BookTown#90]
in philosophy page the books are not arranged correctly please assign me this issue @Karamraj 
![Screenshot (785)](https://github.com/Karamraj/BookTown/assets/124120102/51359c93-1983-41ce-ade1-298ee880960a)

**Comment by bhaskarblur** [comment]
I see the issue is legit, but your issue name & description is not descriptive, please write a better title & description like book cards layout issue in philosphy page from next time.

Thanks

**Comment by khadar1020** [comment]
I mean the boxes in which the book picture and the book name are written which we basically call divs(in programming) are not arranged correctly as we can see in the picture they overlap with the footer and the header so I will arrange them in a proper way @bhaskarblur
